# Generated by Django 3.2.8 on 2021-10-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('talent', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'url_list',
                'managed': False,
            },
        ),
    ]
