# Generated by Django 3.2.8 on 2021-10-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_urllist'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoreStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ignore_station',
                'managed': False,
            },
        ),
    ]
