# Generated by Django 3.2.8 on 2021-10-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_auto_20211011_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvScrape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('talent', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=25)),
                ('station', models.CharField(max_length=50)),
                ('program_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'tv_scrape',
                'managed': False,
            },
        ),
    ]
